### PR TITLE
Generate configmap based on replica count

### PR DESCRIPTION
**Pull request by danisla**
- Add memcached chart dependency containing fix for `replicaCount`
- Generate the configmap automatically per the value of `memcached.replicaCount`
- Add annotation to the statefulset so that it recreates pods when the configmap changes.

The mcrouter pods now get recreated on upgrade when scaling memcached.

```
helm upgrade --set memcached.replicaCount=2 --recreate-pods mcrouter/
```

### CODE REVIEW

**Comment by danisla** [comment]
FYI, the PR on the k/charts repo that fixes the memcached chart has been merged: https://github.com/kubernetes/charts/pull/1772

You can use a requirements.yaml like the one below to reference the dependency:

```yaml
dependencies:
  - name: memcached
    version: 1.2.1
    repository: https://kubernetes-charts.storage.googleapis.com/
```

**Comment by jphalip** [comment]
Thanks @danisla!

I was looking into something similar, however I ran into a few issues.

First, mcrouter has lots of features and therefore the configuration JSON can be quite complex. You can have multiple pools, control the routes, etc. See the various options here: https://github.com/facebook/mcrouter/wiki/Config-Files

So the template used in the PR is a little too rigid, and I think it's best to let the user provide the entire configuration JSON directly.

So instead I looked into doing this in the `configmap.yaml`:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-configmap
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config-str: {{ .Values.mcrouter.configStr }}
```
... and then pass the configuration as a value:

```
helm install mcrouter-helm-chart/mcrouter --name=myproxy --set mcrouter.configStr=string({"pools":{"A":{"servers":["mycache-memcached-0.mycache-memcached.default.svc.cluster.local:11211","mycache-memcached-1.mycache-memcached.default.svc.cluster.local:11211","mycache-memcached-2.mycache-memcached.default.svc.cluster.local:11211"]}},"route":"PoolRoute|A"})'
```
The problem is that it returns the following error:
```
-bash: syntax error near unexpected token `('
```

I think this is because values are parsed against a special syntax, and Helm tries to parse the provided JSON string as if it were following that syntax. Ideally it'd be great if there was a way to tell Helm to process the value just as a raw string instead of trying to parse it, but I'm not sure if that's possible. Could that be a viable feature request for Helm?

So this is why I had resorted to assume that the user would have to create the configmap manually instead, with something like this:

```
kubectl create configmap myproxy-mcrouter-configmap --from-literal=config-str='{"pools":{"A":{"servers":["mycache-memcached-0.mycache-memcached.default.svc.cluster.local:11211","mycache-memcached-1.mycache-memcached.default.svc.cluster.local:11211","mycache-memcached-2.mycache-memcached.default.svc.cluster.local:11211"]}},"route":"PoolRoute|A"}'
```

... but then I don't know how to automatically generate a hash based on that configmap, since it's loaded in memory instead of stored in a file. It'd be great if we could do something like this:

```yaml
  annotations:
    checksum/config: {{ <LOAD CONFIGMAP FROM MEMORY> | sha256sum }}
```

Would there be a workaround to achieve that?

Another option would be to do something simple and dumb like this:

```yaml
  annotations:
    configmap-version: {{ .Values.mcrouter.configmapVersion }}
```

... and then let the user explicitly provide the current configmap version:

```
CONFIGMAP_VERSION=$(kubectl get configmap myproxy-mcrouter-configmap -o jsonpath="{.metadata.resourceVersion}")

helm install mcrouter-helm-chart/mcrouter --name=myproxy --set mcrouter.configmapVersion=$CONFIGMAP_VERSION
```

... but that'd be kind of a shame as it'd be a pretty counter-intuitive, leaky abstraction.

Thoughts?

**Comment by danisla** [comment]
Passing JSON structures via command line arguments still feels kind of clunky and could trip users up.

You could automate the common case where the config is generated with sensible defaults and a pool matching the number of memcachd replicas, like what I have in this PR. Then have an optional value that gives the user the ability to BYO config by passing `--set configFile=myconfig.json` As long as `myconfig.json` lives in the root of the chart dir, you can use it in the configmap.

You should also consider using the `--config-file` arg to mcrouter to pass the config as a file rather than a string. And use the configmap to lay down the file rather than an env var.

I pushed a [new commit](https://github.com/jphalip/mcrouter-helm-chart/pull/1/commits/68e7948b683bc159d0bad929c96ff7028396d0ad) showing how to do the conditional in the configmap to switch between generated vs provided and how to mount the configmap files.

**Comment by jphalip** [comment]
@danisla Thanks a lot, that makes perfect sense. I've merged your PR and added a few changes: https://github.com/jphalip/mcrouter-helm-chart/commit/9d8c0e7d515b8b2f439c744f7b30e9984f755ebf

Most notably, I've removed the dependency from the memcached chart so that this chart can work standalone and to allow users to run memcached services other than via the memcached chart.

Let me know what you think!

**Pull request merged**
